### ISSUE TITLE
Text wrap?

### ISSUE THREAD

**Issue by ajboni** [NikitaIvanovV/ctpv#1]
Hello, thanks for this great tool!
As lf plugin, on text previews, It would be nice to have some sort of text wrap (or maybe thats a lf thing?)

![image](https://user-images.githubusercontent.com/12578313/174502079-f7c11805-c46f-473e-be6c-eedd959d4023.png)

it wraps correctly as standalone though

![image](https://user-images.githubusercontent.com/12578313/174501992-e6c09629-3040-44ba-b45b-99eedd9eb7d2.png)

**Comment by NikitaIvanovV** [comment]
That needs to be implemented into preview. Which one of text preview programs do you have installed on the system? You can see the list of all the available ones in the README.

**Comment by ajboni** [comment]
The problematic one is `highlight`. Removed that, installed `bat` and works as expected, also found some error messages with `source-highlight` only. #2 
Thanks!!

**Comment by NikitaIvanovV** [comment]
It turns out highlight doesn't have an option to set output width (to enable text wrapping) while bat does. I could pipe output of `highlight` into some external program to add it but I think it would be better to leave it as is. Those who need text wrapping can use bat as you do.
