### ISSUE TITLE
The previewer for Office files does not work.

### ISSUE THREAD

**Issue by pu-007** [NikitaIvanovV/ctpv#10]
It keeps showing "Loading..." . Does it usually have to take a long time?

**Comment by NikitaIvanovV** [comment]
It takes some time but not much. Although I tested with very simple files... Could you make a simple file yourself (e.g., a document with only one sentence of text) and see if the preview gets generated for it?

**Comment by NikitaIvanovV** [comment]
I've looked into it and it turned out there was an error on my part that caused the infinite loading. It should be fixed now.

**Comment by pu-007** [comment]
> I've looked into it and it turned out there was an error on my part that caused the infinite loading. It should be fixed now.

Thanks! It's working pretty well now.
