### ISSUE TITLE
Compilation Error: openssl/md5.h: No such file or directory

### ISSUE THREAD

**Issue by thalha-dev** [NikitaIvanovV/ctpv#11]
I have openssl installed in my machine. And I am not  a C dev. Help

make[1]: Leaving directory '/home/thalha/source-installed/ctpv/embed'
cc -O2 -MD -Wall -Wextra -Wno-unused-parameter   -c -o src/ctpv.o src/ctpv.c
src/ctpv.c:9:10: fatal error: openssl/md5.h: No such file or directory
    9 | #include <openssl/md5.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/ctpv.o] Error 1

**Comment by thalha-dev** [comment]
After installing this package the error gone.

**libssl-dev**

**Comment by NikitaIvanovV** [comment]
Glad you figured it out yourself! Some Linux distros (such as Ubuntu) need special files called "header files"  to build a program that uses a library and `libssl-dev` probably contains such files for openssl.
