### ISSUE TITLE
`ctpv -s` requires Ueberzug?

### ISSUE THREAD

**Issue by mangkoran** [NikitaIvanovV/ctpv#12]
I got the following error
```
> ctpv -s 69
cptv: ueberzug not installed
```
Does it requires ueberzug for running server? I want to use its kitty backend.

**Comment by NikitaIvanovV** [comment]
Kitty backend doesn't require running the server. The server currently is only required for using ueberzug backend, this is why `ctpv -s` returns an error if ueberzug is not installed.

**Comment by mangkoran** [comment]
So what is the correct setup to use `ctpv` as `lf` previewer, using `kitty` backend? As the tutorial in `ctpv` man page and `lf` wiki use `ctpv -s`.

**Comment by NikitaIvanovV** [comment]
Just remove the `ctpv -s` in the config

**Comment by NikitaIvanovV** [comment]
It should not happen though, ideally you should leave the line as is even if you use another backend. Thank you for reporting the bug, will fix!

Meanwhile, as I've said, you can try removing the `ctpv -s` line.

**Comment by mangkoran** [comment]
Thank you @NikitaIvanovV . However, I have tried removing `ctpv -s` line (and the `ctpvquit`), but image preview still not showing in `lf`.

**Comment by NikitaIvanovV** [comment]
This is weird. Do other previews (like text) work? If they do I doubt it's lf issue. It's probably a bug in ctpv. What version of lf and kitty do you use?

**Comment by mangkoran** [comment]
Yes. Other preview such as text works.

**Comment by NikitaIvanovV** [comment]
What happens if you run `ctpv file.png 10 10 10 10` ?

**Comment by mangkoran** [comment]
It shows the image but small.

**Comment by NikitaIvanovV** [comment]
Could you please try installing kitty 0.25.2 and see if it works?

**Comment by NikitaIvanovV** [comment]
No, I simply noticed that we have different versions and I assumed that the bug had something to do with it. Thank you for testing! I will look into why it doesn't work for an older versions of kitty.

**Comment by NikitaIvanovV** [comment]
No, I think it would be better if this issue was closed and a new one with a proper title opened.
