### ISSUE TITLE
Kitty backend doesn't work for kitty v0.21.2

### ISSUE THREAD

**Issue by NikitaIvanovV** [NikitaIvanovV/ctpv#13]
Context: https://github.com/NikitaIvanovV/ctpv/issues/12

**Comment by NikitaIvanovV** [comment]
@mangkoran Fixed in 17392c53596f91bbbff2defd84ab8cd99d105c44, could you please check if it works?

**Comment by mangkoran** [comment]
Still not working :(

**Comment by NikitaIvanovV** [comment]
I assume you previously build and installed the program by running `sudo make install`. Could you try running `sudo make clean` (effectively removing all generated files) and then `make ctpv` to see if files have proper ownership?

**Comment by mangkoran** [comment]
Unfortunately, now I have no sudo access.

In my opinion, it could be better if user have the option to whether install it system wide (root) or local user only. Changing below
https://github.com/NikitaIvanovV/ctpv/blob/688703db50192c8bab393d8f8e77365f66ea08f0/Makefile#L1

to `$HOME/.local` (cmiiw) should be enough for the local user installation.

**Comment by NikitaIvanovV** [comment]
> Unfortunately, now I have no sudo access (work PC).

If you don't have sudo access, how did those files end up being owned by root in the first place? :thinking:

> In my opinion, it could be better if user have the option to whether install it system wide (root) or local user only.

A user already has this option! This is why I added the `PREFIX` variable. You can also just run `make PREFIX=~/.local install`, without editing the Makefile.

**Comment by mangkoran** [comment]
> If you don't have sudo access, how did those files end up being owned by root in the first place? thinking


I had sudo access. I need to request to IT department beforehand. Now my access has been revoked
> A user already has this option! This is why I added the PREFIX variable. You can also just run make PREFIX=~/.local install, without editing the Makefile.

My bad. However, I think it can be better if this info is also put in the readme (for better clarity. User need to check the Makefile first before they know they can install locally :D).

**Comment by NikitaIvanovV** [comment]
Thank you for suggestions!
