### ISSUE TITLE
Better image previews on Wayland

### ISSUE THREAD

**Issue by brccabral** [NikitaIvanovV/ctpv#14]
Hi,
lf on wayland uses chafa not ueberzug, thus the preview has low resolution.
Changing the login to Xorg it seems to use ueberzug and preview has good resolution.
But I don't know what software is causing the issue.
Where is the problem? On ueberzug, on wayland, on lf or on ctpv?

**Comment by NikitaIvanovV** [comment]
Ueberzug is Xorg only, it's not supported on Wayland. You can try using Kitty terminal, it supports normal image rendering on Wayland. I know that there are some protocols that other terminals use for rendering images on Wayland, I will look into how to implement those into ctpv.

**Comment by donbex** [comment]
> I know that there are some protocols that other terminals use for rendering images on Wayland, I will look into how to implement those into ctpv.

If it helps, Wezterm supports the [iTerm image protocol](https://wezfurlong.org/wezterm/imgcat.html) and comes with a an example renderer utility like icat.

**Comment by dragove** [comment]
maybe [ncls](https://github.com/dankamongmen/notcurses) can be a great tool?

**Comment by NikitaIvanovV** [comment]
Many terminals seem to support [Sixel format](https://en.wikipedia.org/wiki/Sixel) but lf, for which ctpv was written, [doesn't support it](https://github.com/gokcehan/lf/issues/675).

There was an attempt to [add support](https://github.com/gokcehan/lf/pull/840) for Sixel to lf but it didn't work out.

**Comment by dragove** [comment]
> Actually, previews do work on xwayland terminals like alacritty, kitty, urxvt, etc. But on "wayland only" terminals such as [foot](https://codeberg.org/dnkl/foot/issues/1217), I still have issues with previewing.

For wayland, you can use `kitty`, kitty's icat utility can help you to preview images. Also, `wezterm` supports iTerm2 inline images protocol. I don't know if other terminal emulators have similar things.

I tested `ncls` and `chafa` in `foot` terminal, `ncls` has better color however it is not as good as it in other terminal emulators.

**Comment by NikitaIvanovV** [comment]
> But on "wayland only" terminals such as [foot](https://codeberg.org/dnkl/foot/issues/1217), I still have issues with previewing.

Could you please elaborate which issues you have when using foot? Image previews are low resolution or don't work at all?

**Comment by NikitaIvanovV** [comment]
Guys, I've found a potential solution: https://github.com/NikitaIvanovV/ctpv/issues/25#issuecomment-1325711574

You need to:
* Use a terminal that supports sixel format (e.g., [foot](https://codeberg.org/dnkl/foot))
* Install [this fork](https://github.com/horriblename/lf) of lf that supports sixel
* Update ctpv to the latest commit and add `set autochafa` option in your ctpv config.

**Comment by NikitaIvanovV** [comment]
Fixed! See docs on how to setup here: https://github.com/NikitaIvanovV/ctpv/blob/0c882097f672b8d07c96f95296d904f3d5a81083/README.md#wayland
