### ISSUE TITLE
Previewing

### ISSUE THREAD

**Issue by harishnkr** [NikitaIvanovV/ctpv#15]
Cannot get image preview for .svg files.
The script for the svg can be read using ctpv not as a preview but directly from the commandline.
But it cant be previewed inside the file manager (lf in my case).

**Comment by NikitaIvanovV** [comment]
Fixed in 230f6254c5fe19e110e9cf6660fc7c8527cad6a5

**Comment by NikitaIvanovV** [comment]
Could you please test if it works?

**Comment by harishnkr** [comment]
Yep. It works perfectly. I use Arch Linux, if it helps at any point.
