### ISSUE TITLE
[help] gpg-encrypted

### ISSUE THREAD

**Issue by yyy33** [NikitaIvanovV/ctpv#16]
Which package should I install on arch linux?tangk you

**Comment by NikitaIvanovV** [comment]
https://aur.archlinux.org/packages/ctpv-git

You will probably need an AUR helper to install it (I recommend yay or paru).

**Comment by yyy33** [comment]
> 

I already have yay installed on my computer, but I can't find the package when I run the following command
````
yay -S gpg-encrypted
```

**Comment by NikitaIvanovV** [comment]
You need to run `yay -S ctpv` to install the program.

If you want to preview gpg-encrypted files, you need to also install `gpg` package by running `pacman -S gpg` (however, I bet the package is already installed on your system).

**Comment by yyy33** [comment]
> You need to run `yay -S ctpv` to install the program.
> 
> If you want to preview gpg-encrypted files, you need to also install `gpg` package by running `pacman -S gpg` (however, I bet the package is already installed on your system).

Yes, you are right, it is already installed. Thanks!
