### ISSUE TITLE
Can't work in nvim terminal

### ISSUE THREAD

**Issue by yyy33** [NikitaIvanovV/ctpv#17]
![22](https://user-images.githubusercontent.com/51548147/193386077-c7d48102-7425-43ff-9747-32e689f59dbf.png)

My pdf, office, picture preview of the effect are displayed like this, my nvim version is NVIM v0.7.2

**Comment by NikitaIvanovV** [comment]
Do you use Xorg or Wayland?

**Comment by yyy33** [comment]
> Do you use Xorg or Wayland?

i am use xorg now

**Comment by yyy33** [comment]
> Do you use Xorg or Wayland?

But I can preview the images normally using ranger and w3m

**Comment by yyy33** [comment]
> Do you use Xorg or Wayland?

![55](https://user-images.githubusercontent.com/51548147/193408606-8e2773ef-b46a-436f-88bc-cd3665a8a972.png)

**Comment by NikitaIvanovV** [comment]
Does ctpv image previews work in other terminals? Did you install `ueberzug` package?

**Comment by yyy33** [comment]
> Does ctpv image previews work in other terminals? Did you install `ueberzug` package?

yes, i installed, it is work in alacritty

**Comment by NikitaIvanovV** [comment]
Could you please send a screenshot showing that it works fine in Alacritty?

**Comment by yyy33** [comment]
> Could you please send a screenshot showing that it works fine in Alacritty?

This is `alacritty` work with `ueberzug`
![5555](https://user-images.githubusercontent.com/51548147/193491335-a1c93c45-f4b4-406a-822f-2a096db44c7a.png)

**Comment by yyy33** [comment]
> Could you please send a screenshot showing that it works fine in Alacritty?

This is nvim terminal work with ueberzug, it is show nothing
![6666](https://user-images.githubusercontent.com/51548147/193491417-0c94b736-1b89-4748-9c2d-d312f1f8a16e.png)

**Comment by yyy33** [comment]
e

> Could you please send a screenshot showing that it works fine in Alacritty?

This is alacritty work with chafa, Cannot display properly
![34](https://user-images.githubusercontent.com/51548147/193491679-d2ba2d3b-38d1-4177-8144-4866177ced89.png)

**Comment by yyy33** [comment]
ee

> Could you please send a screenshot showing that it works fine in Alacritty?

This is `nvim terminal` work whith `chafa`, Cannot display properly too
![88](https://user-images.githubusercontent.com/51548147/193491885-8eeca8d5-960d-412a-b296-8e6edb1c2603.png)

**Comment by NikitaIvanovV** [comment]
> This is alacritty work with chafa, Cannot display properly

Actually, it is how image previews with chafa are supposed to look. It draws an image with terminal characters; this method works in every terminal and system but is of bad quality.

I've tested and ueberzug image previews work well in nvim terminal. Could you please share more information about your system? Linux distribution version, ueberzug version?

**Comment by yyy33** [comment]
> > This is alacritty work with chafa, Cannot display properly
> 
> Actually, it is how image previews with chafa are supposed to look. It draws an image with terminal characters; this method works in every terminal and system but is of bad quality.
> 
> I've done some testing and ueberzug image previews work well in nvim terminal. Could you please share more information about your system? Linux distribution version, ueberzug version?



> 

I found the reason, I made a mistake and ignored the existence of the terminal multiplexer.
I used neovim and abduco instead of tmux as my terminal taker and executed the following command
```
alacritty -e abduco -e '' -A nmux nvim +terminal
```
At this point opening lf does not allow you to use ctpv to preview the image properly.

Then when I don't use abduco:
```
alacritty -e nvim +terminal
```
I can preview the image with ctpv, everything works fine

**Comment by yyy33** [comment]
> > This is alacritty work with chafa, Cannot display properly
> 
> Actually, it is how image previews with chafa are supposed to look. It draws an image with terminal characters; this method works in every terminal and system but is of bad quality.
> 
> I've done some testing and ueberzug image previews work well in nvim terminal. Could you please share more information about your system? Linux distribution version, ueberzug version?


I am using arch linux
```
❯ ueberzug version
18.1.9

❯ uname -a
Linux x550vc-yyy 5.18.16-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000 x86_6

❯ pacman -Q xorg-server
xorg-server 21.1.4-1

❯ pacman -Q neovim
neovim 0.8.0-3

❯ pacman -Q abduco
abduco 0.6-6

❯ pacman -Q alacritty
alacritty 0.10.1-2

❯ yay -Q lf
lf-bin 27-1


```

**Comment by NikitaIvanovV** [comment]
Do image previews work if you use tmux?

**Comment by yyy33** [comment]
> Do image previews work if you use tmux?

yes, it work
![hh](https://user-images.githubusercontent.com/51548147/195881665-c95b9ea5-6daf-42a8-8dd4-7fb04cc37c41.png)

**Comment by yyy33** [comment]
> No issues with `arch / alacritty / lf / chafa`
> 
> ![](https://user-images.githubusercontent.com/117489882/200796719-b74c043e-c83a-4583-b6dd-9d68abf38df7.png)
> 
> Although the blockyness is chafa being lazy & quick. Ueberzug works fine too.

Yes, I think the problem is with `abduco`, as soon as you use it you can't preview the images, but its maintainer, `martanne`, stopped being active two years ago

**Comment by yyy33** [comment]
> I don't understand you btw. What's `abduco` ? I'm using `chafa` to preview images. I think you don't need abduco for chafa. It should work fine anywhere, since chafa only generates lowres.

abduco is a terminal multiplexer that does not preview images when working with neovim terminations

**Comment by NikitaIvanovV** [comment]
> Yes, I think the problem is with `abduco`, as soon as you use it you can't preview the images, but its maintainer, `martanne`, stopped being active two years ago

You are right, it seems like abduco and ueberzug don't work well together and the issue is not on the side of ctpv.

**Comment by yyy33** [comment]
> > Yes, I think the problem is with `abduco`, as soon as you use it you can't preview the images, but its maintainer, `martanne`, stopped being active two years ago
> 
> You are right, it seems like abduco and ueberzug don't work well together and the issue is not on the side of ctpv.

Yes, the maintainers of both programs are no longer active, so I'll close this issue for now. Thank you.

**Comment by yyy33** [comment]
> Then try tmux I guess.

Thanks, tmux is too complicated for me, I just need a simple terminal multiplex
