### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by thisismygitrepo** [NikitaIvanovV/ctpv#18]
08:48:06 alex@alex-xps ctpv ±|master|→ sudo make install
make -C embed
make[1]: Entering directory '/home/alex/ctpv/embed'
make[1]: 'embed' is up to date.
make[1]: Leaving directory '/home/alex/ctpv/embed'
cc -o src/ctpv.o src/ctpv.c -c -O2 -MD -Wall -Wextra -Wno-unused-parameter
src/ctpv.c:2:10: fatal error: magic.h: No such file or directory
    2 | #include <magic.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:55: src/ctpv.o] Error 1

**Comment by NikitaIvanovV** [comment]
You need to install `libmagic` library. Which Linux distribution do you use?

**Comment by NikitaIvanovV** [comment]
Another issue similar to this: https://github.com/NikitaIvanovV/ctpv/issues/23
