### ISSUE TITLE
When make install, get error message: "src/ctpv.c:2:10: fatal error: magic.h: No such file or directory"

### ISSUE THREAD

**Issue by og900aero** [NikitaIvanovV/ctpv#23]
I cannot install ctpv, because get error message:

$ sudo make install
make -C embed
make[1]: Entering directory '/home/shyciii/ctpv/embed'
make[1]: 'embed' is up to date.
make[1]: Leaving directory '/home/shyciii/ctpv/embed'
cc -o src/ctpv.o src/ctpv.c -c -O2 -MMD -Wall -Wextra -Wno-unused-parameter
src/ctpv.c:2:10: fatal error: magic.h: No such file or directory
    2 | #include <magic.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:55: src/ctpv.o] Error 1

**Comment by NikitaIvanovV** [comment]
You need to install `libmagic` library. A similar issue: https://github.com/NikitaIvanovV/ctpv/issues/4 . If you don't know how to install it, tell me which Linux distribution you use and I will try to find a package you need to install to obtain the library.

**Comment by og900aero** [comment]
I use Debian 11.5 stable. I try libmagic1 package, but error still remain.

**Comment by NikitaIvanovV** [comment]
Try also installing `libssl-dev`.

**Comment by og900aero** [comment]
Thx, work like a charm!
