### ISSUE TITLE
User config `PREFIX` rather than system bin

### ISSUE THREAD

**Issue by CharlesChiuGit** [NikitaIvanovV/ctpv#24]
https://github.com/NikitaIvanovV/ctpv/blob/6d5c14d279a71d676270151d218efef067733921/Makefile#L1

Is there a reason fixing prefix to `/usr/bin`, or it's possible to be a pass-in option? I would really like it to be a local only program, cause people don't have sudo privilege all the time.

Thanks for the great work!

**Comment by NikitaIvanovV** [comment]
Yep, it's not necessary to install it, you can just type `make` and out the put the compiled binary wherever you want.

**Comment by CharlesChiuGit** [comment]
ys, that's what I had done. 😂
Sorry, not quite familiar with makefiles.
