### ISSUE TITLE
Aur complains about PGP

### ISSUE THREAD

**Issue by se7en-x230** [NikitaIvanovV/ctpv#28]
==> ERROR: One or more PGP signatures could not be verified!

**Comment by NikitaIvanovV** [comment]
Are you trying to install the AUR package? If yes, try running `gpg --recv-keys 701DE74D84F87EE1BC91CD216E656AC5B97B5133`.

**Comment by se7en-x230** [comment]
Yes and thanks

**Comment by se7en-x230** [comment]
![IMG_20221219_061920](https://user-images.githubusercontent.com/69777713/208324675-48db23fb-d338-497c-b1fc-8f443968adf7.jpg)

Nope still complaining. 
I use the AUR package for a while without trouble. The signature must have changed with the last release.

**Comment by NikitaIvanovV** [comment]
I've merged a pull request recently and I see that that commit has no signature... Will fix!

**Comment by NikitaIvanovV** [comment]
Could you please try again?

**Comment by se7en-x230** [comment]
Perfect. Works fine again. Thanks for the fast fix
