### ISSUE TITLE
"Error: The --place option can only be used with a single image, not 2"

### ISSUE THREAD

**Issue by hiimsergey** [NikitaIvanovV/ctpv#32]
Hello,
At first, thank you very much for the project, I used it with the kitty terminal in the lf file manager.
After a certain time, presumably an update, ctpv throws this error (title) after running

`ctpv /path/to/image`

Note that I don't use any flags and only point to one image.
But when I actually run the flag:

`ctpv --place /path/to/image`

it throws:

`ctpv: invalid option -- '-'`

**Comment by karmanxyz** [comment]
had the same problem. it has something to do with the new kitty 0.27.0 version, i reverted back to 0.26.5 and the problem goes away.

**Comment by hiimsergey** [comment]
@karmanxyz Ah I see. There was a kitty update indeed.

Yesterday I tried ranger FM with python-pillow and it worked and I think I'll keep using this on kitty.

**Comment by Gajus84** [comment]
@hiimsergey  Maybe the Issue should stay open, as downgrading Kitty or using a different method, are just a quick fix, but not a solution of it?

**Comment by hiimsergey** [comment]
Do you think, this is still a ctpv issue instead of kitty? If so, I'll reopen it

**Comment by Gajus84** [comment]
I do, because the command itself eg. "kitty +kitten icat --transfer-mode file --align left --place "100x100@100x100" picture-to-display" still works on 0.27.0.

**Comment by Andrew15-5** [comment]
I can confirm that `lf` r28 in `kitty` 0.27.1 has the same problem, but in `kitty` 0.26.5 does not, with one note: I had to do `echo set forcekitty > ~/.config/ctpv/config`. Otherwise, both version are not working for me (after a quick `Loading...` there is no preview at all).
