### ISSUE TITLE
Support for pdf-s using LibreOffice directly

### ISSUE THREAD

**Issue by DusanLesan** [NikitaIvanovV/ctpv#33]
In case when users use LibreOffice from app images, they might not have poppler installed. It would be nice to go through LibreOffice as  second option

**Comment by NikitaIvanovV** [comment]
I disagree, LibreOffice is a huge program and I believe that running it to generate a jpeg preview from a pdf file simply won't be fast enough. Installing poppler would be much more efficient.

**Comment by DusanLesan** [comment]
I'll close the issue then. I thought that it could serve as a fallback.
