### ISSUE TITLE
PDF previews broken by unknown flags

### ISSUE THREAD

**Issue by BrannigansLaw** [NikitaIvanovV/ctpv#36]
Hi, great program. Really easily makes lf into the best terminal file manager. 

PDF image previews aren't working for me due to pdftoppm complaining about flags. I was able to fix it in my case by removing "-tiffcompression jpeg" from "ctvp/sh/prev/pdf.sh".

I'm building it from source on gentoo linux. Anyway, thought I would let you know. Godspeed Ivanov.

**Comment by NikitaIvanovV** [comment]
Thanks! Removed the flag.
