### ISSUE TITLE
cannot preview readme files with glow

### ISSUE THREAD

**Issue by harishnkr** [NikitaIvanovV/ctpv#40]
Tried to use [glow](https://github.com/charmbracelet/glow): for markdown previews.
Does not work 

config is as follows:

```
preview glow .md {{
    glow < "$f" 
}}

```

It works when invoked via command like without lf.
Terminal : kitty

**Comment by harishnkr** [comment]
Never mind, I was able to view it after specifying the style (dark or light)
I guess i can close the issue

**Comment by NikitaIvanovV** [comment]
Glad to know you figured it out! Do you think other people might consider this preview useful? If so, maybe we should add it as a built-in preview to ctpv?

**Comment by harishnkr** [comment]
Yes. I honestly think others would find it really beneficial. It works out of the box but there are some features missing in LF that fails to take advantage of text previews.

![2023-03-11_10-00](https://user-images.githubusercontent.com/48408097/224464923-0b4f98d1-09bf-4848-9c27-39e7b0c844a0.png)
![2023-03-11_09-59](https://user-images.githubusercontent.com/48408097/224464928-4bf8e393-8286-4da8-832a-140ffe8d8d1c.png)

**Comment by harishnkr** [comment]
As you can see text wrapping is not functional (maybe i am overlooking some inbuilt features in LF). I used dark theme for the preview (which as i said before must be specified in order to use it). [glow](https://github.com/charmbracelet/glow) does not currently render images, but I am pretty sure it will work in the future. 

But I cant currently view images from markdown files via mdcat either.

![2023-03-11_10-10](https://user-images.githubusercontent.com/48408097/224465259-8207f586-1163-4bc5-a87c-823866438fbe.png)

I will add a pull request for glow as a previewer for ctpv if you are okay with it. I also hope LF make scroll preview a thing. If ctpv can make a feature for scrolling as well, it would be great.

**Comment by NikitaIvanovV** [comment]
Yes, feel free to open a pull request! You need to add a script to `sh/prev/` and add a new entry to `previews.h`.

**Comment by harishnkr** [comment]
Opened pull request [here](https://github.com/NikitaIvanovV/ctpv/pull/44)
