### ISSUE TITLE
Could you tag another release?

### ISSUE THREAD

**Issue by Nehctarg** [NikitaIvanovV/ctpv#42]
# Why
The last tagged release is -right now- 50 commits behind. Using this release is obviously not really ideal, as all the progress from these 50 commits would go to waste. 

# Why installing from source isn't an option
I use nixos, which makes your OS deterministic, thus directly installing from the tip of your master branch is impossible. That's why we specify the release version directly. Using a release over a commit hash is preferred because it leaves the control to decide which features get packaged by the developer

# What I'm asking 
Please tag a new release on a stable commit to allows us to package a slightly newer version.

**Comment by NikitaIvanovV** [comment]
I see. There are a few error which I still want to fix first. Once I do that, I will definitely tag a new version!

**Comment by Nehctarg** [comment]
Great, thank you!

**Comment by NikitaIvanovV** [comment]
Just published `v1.1`!

**Comment by NikitaIvanovV** [comment]
To clarify: do you want to make a package for Nixos?

**Comment by Nehctarg** [comment]
It's actually already packaged (see [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/file-managers/lf/ctpv.nix#L13)), but at version 1.0. I'll open a pr in the next days that updates it to 1.1.

**Comment by NikitaIvanovV** [comment]
Oh, I didn't know the package already exists. Please open a PR with installation instructions! You can use instructions for Arch Linux as a template.

**Comment by Nehctarg** [comment]
Sure, I'm going to do that in the coming days!

**Comment by Nehctarg** [comment]
Added them in #50.
