### ISSUE TITLE
Preview values not taken by LF

### ISSUE THREAD

**Issue by harishnkr** [NikitaIvanovV/ctpv#58]
error shown whenever lf is opened : "preview: value should be empty, 'true', or 'false'"

I am using personal fork of [ST](https://github.com/harishnkr/st) if it helps

Note: I tried it on kitty terminal as well, same problem. I dont think its the terminal's problem.

Not using wayland, and the arch signature is not trusted atm

Thanks anyway

**Comment by NikitaIvanovV** [comment]
I assume it's not an ctpv issue, lf recently updated their syntax for options. You need to change `set preview on/off` to `set preview true/false`.

**Comment by harishnkr** [comment]
Oh you are right, I changed it to true and errors were gone. But previews are still not working, they show up as binary in the previews. I know it's now a separate issue so thanks for sorting the main issue.

**Comment by harishnkr** [comment]
@NikitaIvanovV  you can close the issue but I wanted to mention now that the problem I face is similar to issue #37  . Everything works fine when I try a Tmux session. Looks like the author has stopped working on ueberzug.
