### ISSUE TITLE
[Feature] kitty image preview for animated GIF files only

### ISSUE THREAD

**Issue by Beatsz** [NikitaIvanovV/ctpv#6]
I like the fast image preview for ueberzug and kitty for **animated** gif previews. Kitty is a bit slow when it comes to image preview compared to ueberzug

**Comment by NikitaIvanovV** [comment]
Just added `forcekittyanim` option: 78dd61e73bd2e8a690a01b191174bffcbbe8b324, please check if it works.

**Comment by Beatsz** [comment]
![Peek 2022-07-08 00-03](https://user-images.githubusercontent.com/31421575/177871132-8fabc0cd-4602-4af7-95b2-2fce652a4b76.gif)

cleaner issue. I didn't face this issue with either forcekitty or ueberzug option

**Comment by Beatsz** [comment]
yep it works
