### ISSUE TITLE
Low resolution blocky preview for all visual file types (video, image, pdf, doc etc..)

### ISSUE THREAD

**Issue by Argus-Khan** [NikitaIvanovV/ctpv#62]
Can anyone help? I am getting really weird low resolution previews for all visual file types, I'm using kitty terminal. Viewing images on kitty works fine with icat.

**Image**
![Screenshot_2023-07-27_03-18-56](https://github.com/NikitaIvanovV/ctpv/assets/93172681/7ad55557-170a-44e7-bc28-cddf66d689b8)

**video**
![Screenshot_2023-07-27_03-20-28](https://github.com/NikitaIvanovV/ctpv/assets/93172681/a946c8e5-0d54-41fa-9b62-cbdc2bffa367)

**PDF**
![Screenshot_2023-07-27_03-20-59](https://github.com/NikitaIvanovV/ctpv/assets/93172681/7256414b-0b50-4b7c-884a-3bc517ef821e)

**Doc**
![Screenshot_2023-07-27_03-22-08](https://github.com/NikitaIvanovV/ctpv/assets/93172681/7e932c27-6d9e-4a4f-9cc7-0a2203888f05)

**Comment by NikitaIvanovV** [comment]
It looks like something chafa could do. Can you try to add `set forcekitty` to your ctpv config?

**Comment by Argus-Khan** [comment]
Unfortunately I can't try that anymore, I was using Linuxmint before but I switched to Fedora 38 a couple of days ago and everything works just fine now. 😅

**Comment by NikitaIvanovV** [comment]
Oh, glad to hear that it's fixed!

**Comment by rxmmah** [comment]
> Oh, glad to hear that it's fixed!
technically it's not fixed, the problem is real
