### ISSUE TITLE
Can't change previewer for tar.gz

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [NikitaIvanovV/ctpv#76]
Trying to use a different previewer for `.tar.gz` but it doesn't work. It's splitting .tar and .gz into different extensions instead of using it as `.tar.gz`

**Comment by Joyje** [comment]
How did you solve this?

**Comment by Joyje** [comment]
Found the solution here:

https://github.com/NikitaIvanovV/ctpv/issues/31
