### ISSUE TITLE
Can you make it preview office(docx xlsx.....etc) file like stpv with libreoffice?

### ISSUE THREAD

**Issue by lfishRhungry** [NikitaIvanovV/ctpv#9]
I used to preview file by stpv in lf. But stpv became orphaned in aur.
And I'm surprised to see ctpv and very appreciate to you!
I think it is important to preview office files for many people in job.
Can you make it preview office(docx xlsx.....etc) file like stpv with libreoffice?

**Comment by NikitaIvanovV** [comment]
`.odt` documents were already supported but I added more in 9e2be65 (specifically `ods`, `fods`, `xls`, `xlsx`, `csv`, `odt`, `fodt`, `doc`, `docx`).

Please let me know if there are more document types you would like me to add.

Note that the files must have a proper extension (e.g., end with `.odt`) for previews to work.

**Comment by lfishRhungry** [comment]
> `.odt` documents were already supported but I added more in [9e2be65](https://github.com/NikitaIvanovV/ctpv/commit/9e2be65d68aac7eaca0629c1d2567570e8868027) (specifically `ods`, `fods`, `xls`, `xlsx`, `csv`, `odt`, `fodt`, `doc`, `docx`).
> 
> Please let me know if there are more document types you would like me to add.
> 
> Note that the files must have a proper extension (e.g., end with `.odt`) for previews to work.

Thanks!!!! you make my workflow awesome~~~~~~

**Comment by lfishRhungry** [comment]
> `.odt` documents were already supported but I added more in [9e2be65](https://github.com/NikitaIvanovV/ctpv/commit/9e2be65d68aac7eaca0629c1d2567570e8868027) (specifically `ods`, `fods`, `xls`, `xlsx`, `csv`, `odt`, `fodt`, `doc`, `docx`).
> 
> Please let me know if there are more document types you would like me to add.
> 
> Note that the files must have a proper extension (e.g., end with `.odt`) for previews to work.

One more thing, I think it would be better to preview slide show files (`.ppt` and `.pptx`)

**Comment by NikitaIvanovV** [comment]
Added: bcde581413009ca10f87ba82fc285fef8f156d11
